sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_shipping_slot_method:
                    name: 'shipping_method'
                    options:
                        custom:
                            slot_delivery:
                                code: 'slot_delivery'
                                name: 'Click''n''Collect'
                                enabled: true
                                channels:
                                    - 'FASHION_WEB'
                                zone: 'WORLD'
                            courier_delivery:
                                code: 'courier_delivery'
                                name: 'Courrier delivery'
                                enabled: true
                                channels:
                                    - 'FASHION_WEB'
                                zone: 'WORLD'
                monsieurbiz_shipping_slot_config:
                    options:
                        custom:
                            fashion_store:
                                name: 'Fashion Store hours'
                                rrules: 
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=6,7,8,9,10,11,12,13,14,15,16;BYMINUTE=0;BYSECOND=0'
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=6,7,8,9,10,11,12,13,14,15;BYMINUTE=15;BYSECOND=0'
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=6,7,8,9,10,11,12,13,14,15;BYMINUTE=30;BYSECOND=0'
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=6,7,8,9,10,11,12,13,14,15;BYMINUTE=45;BYSECOND=0'
                                preparationDelay: 60
                                pickupDelay: 0
                                durationRange: 30
                                availableSpots: 10
                                color: '#5D44DC'
                                shipping_methods:
                                    - 'slot_delivery'
                            courier:
                                name: 'Courier hours'
                                rrules: 
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=5,6,7,8,9,10,11,12,13,14,15,16,17;BYMINUTE=0;BYSECOND=0'
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=5,6,7,8,9,10,11,12,13,14,15,16;BYMINUTE=30;BYSECOND=0'
                                preparationDelay: 60
                                pickupDelay: 30
                                durationRange: 60
                                availableSpots: 10
                                color: '#22B99A'
                                shipping_methods:
                                    - 'courier_delivery'

