sylius_resource:
    resources:
        monsieurbiz_shippingslot.shipping_slot_config:
            classes:
                model: MonsieurBiz\SyliusShippingSlotPlugin\Entity\ShippingSlotConfig
                # form: MonsieurBiz\SyliusShippingSlotPlugin\Form\Type\ShippingSlotConfigType
