sylius_resource:
    resources:
        monsieurbiz_shipping_slot.shipping_slot_config:
            classes:
                model: MonsieurBiz\SyliusShippingSlotPlugin\Entity\ShippingSlotConfig
                form: MonsieurBiz\SyliusShippingSlotPlugin\Form\Type\ShippingSlotConfigType
