services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusShippingSlotPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusShippingSlotPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # ShippingSlotConfigType Form
    MonsieurBiz\SyliusShippingSlotPlugin\Form\Type\ShippingSlotConfigType:
        arguments:
            $dataClass: '%monsieurbiz_shipping_slot.model.shipping_slot_config.class%'
            $validationGroups: ['monsieurbiz']

    # Fixtures
    MonsieurBiz\SyliusShippingSlotPlugin\Fixture\ShippingSlotConfigFixture:
        arguments:
            $exampleFactory: '@MonsieurBiz\SyliusShippingSlotPlugin\Fixture\Factory\ShippingSlotConfigFixtureFactory'

    # Menu item in admin panel
    MonsieurBiz\SyliusShippingSlotPlugin\Listener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Remove shipping slot on cart clean
    MonsieurBiz\SyliusShippingSlotPlugin\Listener\CartsPreRemoveListener:
        tags:
            - { name: kernel.event_listener, event: sylius.carts.pre_remove, method: removeExpiredCartsSlots }
