services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusShippingSlotPlugin\:
        resource: '../../*'

    MonsieurBiz\SyliusShippingSlotPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
