MonsieurBiz\SyliusShippingSlotPlugin\Entity\ShippingSlotConfig:
    properties:
        name:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   Length:
                    min: 2
                    max: 255
                    groups: [monsieurbiz]
        preparationDelay:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   PositiveOrZero:
                    groups: [monsieurbiz]
        pickupDelay:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   PositiveOrZero:
                    groups: [monsieurbiz]
        durationRange:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   GreaterThan:
                    value: 0
                    groups: [monsieurbiz]
        availableSpots:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   GreaterThan:
                    value: 0
                    groups: [monsieurbiz]
        color:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   Regex:
                    pattern: '/#[0-9a-f]{6}/'
                    match: true
                    groups: [monsieurbiz]
